#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && pwd )"
OLD_PWD=$PWD

file="synchro"
cd "$DIR" || exit
capnp compile -oc++ "$file.capnp"
status=$?
if test $status -eq 0
then
  mkdir -p generated
  mv "$file.capnp.c++" "generated/"
  mv "$file.capnp.h" "generated/"
  cd "$OLD_PWD" || exit
exit $status
fi
cd "$OLD_PWD" || exit
