name: Capstone
on: [push]
jobs:
  dependencies:
    runs-on:  ubuntu-latest
    steps:
      - name: install cmake
        run:  sudo apt install cmake

  runs:
    needs:    dependencies
    runs-on:  ubuntu-latest
    steps:
      - name: install google logging library
        run:  sudo apt install -y libgoogle-glog-dev
      - name: install SDL2
        run:  sudo apt install libsdl2-dev
      - name: install Cap'n Proto
        run:  curl -O https://capnproto.org/capnproto-c++-0.9.1.tar.gz; tar zxf capnproto-c++-0.9.1.tar.gz; cd capnproto-c++-0.9.1; ./configure; make -j6 check; sudo make install
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure box2d cmake
        run:  cmake -Hbox2d -Bbox2d/build
      - name: install box2d
        run:  sudo cmake --build box2d/build --target install
      - name: explicitly generate capnp files
        run:  cd lib/Server/; ./gen_proto
      - name: configure cmake
        run:  cmake -H. -Bbuild
      - name: compile the project
        run:  cmake --build build --target Capstone
#      - name: Run the benchmarks
#        run: ./build/Capstone

#  tests:
#    needs: dependencies
#    runs-on:  ubuntu-latest
#    steps:
#      - name: install google logging library
#        run:  sudo apt install -y libgoogle-glog-dev
#      - name: install SDL2
#        run:  sudo apt install libsdl2-dev
#      - name: install Cap'n Proto
#        run:  curl -O https://capnproto.org/capnproto-c++-0.9.1.tar.gz; tar zxf capnproto-c++-0.9.1.tar.gz; cd capnproto-c++-0.9.1; ./configure; make -j6 check; sudo make install
#      - uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - name: configure catch2 cmake
#        run:  cmake -HCatch2 -BCatch2/build -DBUILD_TESTING=OFF
#      - name: build and install catch2
#        run:  sudo cmake --build Catch2/build --target install
#      - name: configure box2d cmake
#        run:  cmake -Hbox2d -Bbox2d/build
#      - name: build and install box2d
#        run:  sudo cmake --build box2d/build --target install
#      - name: explicitly generate capnp files
#        run:  cd lib/Server/; ./gen_proto
#      - name: configure own cmake
#        run:  cmake -H. -Bbuild
#      - name: Build test files
#        run:  cmake --build build --target Test
#      - name: Run the tests
#        run: ./build/Test
